### ISSUE TITLE
Katja Mintenbeck Comments 

### ISSUE THREAD

**Issue by IPCCWG1** [IPCCWG1/AR6-FOD#1]
Katja Mintenbeck Comments should show as  -  Hans Pörtner & TSU

**Sent by Clotilde 24th June -**

Dear Clotilde and all,

can you please  confirm that you received our WGII comments on your WGI AR6 FOD? I guess they will be listed under my name, so could you please change that to be listed as comments by "Hans Pörtner & TSU"?

Thanks a lot & best wishes,

**Comment by karhide-xx** [comment]
Updated the source field in the fod table in the ar6comments database.

UPDATE fod SET source = 'Hans Pörtner & TSU' WHERE userid = 'katja.mintenbeck@ipcc-wg2.awi.de';

SELECT * FROM FOD WHERE Source = 'Katja Mintenbeck'; -- Hans Pörtner & TSU - katja.mintenbeck@ipcc-wg2.awi.de

Zero records returned 

SELECT * FROM FOD WHERE userid = 'katja.mintenbeck@ipcc-wg2.awi.de';

82 records returned
