### ISSUE TITLE
Debra Roberts Comments

### ISSUE THREAD

**Issue by IPCCWG1** [IPCCWG1/AR6-FOD#2]
Debra Roberts Comments should show as  - Debra Roberts and Durban WGII TSU team

**Sent by Anna 25th June -** 

Hi Anna – given how hectic things are the Durban TSU team and I have not been able to get through as much of the WGI FOD as we liked but I have uploaded what we have been able to get through. Please will you ensure when they are entered into the comments spread sheet that they are attributed to “Debra Roberts and Durban WGII TSU team” as they are group comments.
Many thanks
D

**Comment by karhide-xx** [comment]
UPDATE fod SET source = 'Debra Roberts and Durban WGII TSU team' WHERE userid = 'debra.roberts@durban.gov.za';

SELECT * FROM fod WHERE Source = 'Debra Roberts';  

Returns zero records

SELECT * FROM fod WHERE userid = 'debra.roberts@durban.gov.za'; 

Returns 54 rows
